### ISSUE TITLE
404 api endpoint

### ISSUE THREAD

**Issue by estradamarkie** [techwarriorz/MEAN_SocialNetwork_Tutorial#2]
Hi, 

I know this is an old tutorial but I'm trying to follow this tutorial with my own stuff and everytime I send my form its giving me 404 error api/user/signup not found. 

I've created an endpoint in the server.js 
`app.post('api/user/signup', authController.signup);`

**Comment by techwarriorz** [comment]
You just need a '/'....

app.post('/api/user/signup', authController.signup); will work
